##### Core #####
set -g history-limit 10000000
set -g default-shell /opt/homebrew/bin/bash
set -s escape-time 0
set -g focus-events on
set -g renumber-windows on
set -g mouse off
set -g set-clipboard on

##### Prefix and reload #####
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix
bind-key r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

##### Window and pane navigation #####
bind-key -n F2 new-window -c "#{pane_current_path}"
bind-key -n S-F3 swap-window -d -t -1
bind-key -n S-F4 swap-window -d -t +1
bind-key -n F3 previous-window
bind-key -n F4 next-window
bind-key -n F7 copy-mode

# Split panes using | and -
bind-key | split-window -h -c "#{pane_current_path}"
bind-key \\ split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
unbind-key '"'
unbind-key %

# Switch panes using Alt ("option" key in macOS) + arrows (no prefix)
bind-key -n M-Left select-pane -L
bind-key -n M-Right select-pane -R
bind-key -n M-Up select-pane -U
bind-key -n M-Down select-pane -D

##### Status line #####
setw -g window-status-current-style "fg=#000000,bg=white"
set -g status-bg black
set -g status-fg white
set -g status-justify left
set -g status-interval 1
set -g status-right-length 250
set -g status-right " \
#[fg=white,bg=black] #(basename \"#{pane_current_path}\" 2>/dev/null) \
#[fg=white,bg=darkred] #(cd \"#{pane_current_path}\" 2>/dev/null && git rev-parse --abbrev-ref HEAD 2>/dev/null) \
#[fg=black,bg=green] #(command -v aws-profile >/dev/null 2>&1 && aws-profile whoami 2>/dev/null | awk '{if(/>/) print $2}') \
#[fg=black,bg=darkorange] #(command -v kubectl >/dev/null 2>&1 && kubectl config view --minify --output 'jsonpath={..contexts[0].context.cluster}' 2>/dev/null | sed -E 's/.*\\([0-9]{10}\\)://') \
#[fg=black,bg=magenta] #(command -v tmux-mem-cpu-load >/dev/null 2>&1 && tmux-mem-cpu-load --interval 10 -m 0 -a 0 -g 0 2>/dev/null) \
#[fg=black,bg=cyan] #(df -h / 2>/dev/null | awk 'NR==2 {print $4}') \
#[fg=black,bg=pink] #(ipconfig getifaddr en0 2>/dev/null) \
#{battery_color_bg} #{battery_percentage}#{battery_color_bg} #(pmset -g batt 2>/dev/null | awk -F ';' '{print $3}' | awk 'NF' | awk '{print $1}')Hrs"

##### Plugins #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-battery'
run '~/.tmux/plugins/tpm/tpm'
